name: launder_land
description: "A new Flutter project."
publish_to: "none"
version: 1.4.1+1.4.1
environment:
  sdk: ^3.5.2

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_native_splash: ^2.4.6
  persistent_bottom_nav_bar_v2: ^5.3.1
  smooth_page_indicator: ^1.2.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  expansion_tile_group: ^2.2.0
  easy_localization: ^3.0.7+1
  easy_localization_loader: ^2.0.2
  form_validator: ^2.1.1
  dash_flags: ^0.1.1
  country_picker: ^2.0.27
  phone_numbers_parser: ^9.0.3
  keyboard_actions: ^4.2.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  pinput: ^5.0.1
  shared_preferences: ^2.5.3
  badges: ^3.1.2
  basic_utils: ^5.8.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  loader_overlay: ^5.0.0
  flutter_inappwebview: ^6.1.5
  google_maps_flutter: ^2.12.1
  geolocator: ^13.0.4
  uuid: ^4.5.1
  http: ^1.3.0
  flutter_cart: ^0.0.9
  url_launcher: ^6.3.1
  easy_stepper: ^0.8.5+1
  flutter_svg: ^2.0.17
  firebase_app_check: ^0.3.2+5
  flutter_launcher_icons: ^0.14.3
  flutter_floating_bottom_bar: ^1.2.1+1
  custom_sliding_segmented_control: ^1.8.5
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  custom_lint: ^0.7.3
  riverpod_generator: ^2.6.4
  riverpod_lint: ^2.6.4
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/navBar/
    - assets/icons/profile/
    - assets/translations/
    - assets/icons/order/

  fonts:
    - family: Google-Sans
      fonts:
        - asset: assets/fonts/Google-Sans/ProductSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/Google-Sans/ProductSans-Light.ttf
          weight: 200
        - asset: assets/fonts/Google-Sans/ProductSans-Light.ttf
          weight: 300
        - asset: assets/fonts/Google-Sans/ProductSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Google-Sans/ProductSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Google-Sans/ProductSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/Google-Sans/ProductSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Google-Sans/ProductSans-Black.ttf
          weight: 800
        - asset: assets/fonts/Google-Sans/ProductSans-Black.ttf
          weight: 900
